openapi: 3.0.3
info:
  title: Student API
  description:
    A API for the beautiful Student API
  version: 1.0.0
servers:
  - url: 'https'
tags:
  - name: student
    description: Students Info
  - name: course
    description: Courses Info
paths:
  /student:
    get:
      tags:
        - student
      summary: Get all students
      description: Get all students
      operationId: getStudents
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
    post:
      tags:
        - student
      summary: Create a student
      description: Create a student
      operationId: createStudent
      requestBody:
        description: Student object that needs to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
components:
    schemas:
        Student:
          type: object
          required:
            - id
            - name
            - email
            - course
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
            email:
              type: string
            course:
              type: string
        Course:
          type: object
          required:
            - id
            - name
            - description
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
            description:
              type: string